// This file is auto-generated from sewing.ini. Do not edit manually.
#ifndef NEEDLE_LIMITS_OVERRIDE_H
#define NEEDLE_LIMITS_OVERRIDE_H

#undef NEEDLE_DEFAULT_V_MAX_DFLT
#define NEEDLE_DEFAULT_V_MAX_DFLT 3.289474

#undef NEEDLE_DEFAULT_A_MAX_DFLT
#define NEEDLE_DEFAULT_A_MAX_DFLT 1.644737

#undef NEEDLE_DEFAULT_J_MAX_DFLT
#define NEEDLE_DEFAULT_J_MAX_DFLT 3289.473684

#undef NEEDLE_POS_V_MAX_DFLT
#define NEEDLE_POS_V_MAX_DFLT 3.289474

#undef NEEDLE_POS_A_MAX_DFLT
#define NEEDLE_POS_A_MAX_DFLT 1.644737

#undef NEEDLE_POS_J_MAX_DFLT
#define NEEDLE_POS_J_MAX_DFLT 3289.473684

#undef NEEDLE_PLAN_V_MAX_DFLT
#define NEEDLE_PLAN_V_MAX_DFLT 2.467105

#undef NEEDLE_PLAN_A_MAX_DFLT
#define NEEDLE_PLAN_A_MAX_DFLT 1.233553

#undef NEEDLE_PLAN_J_MAX_DFLT
#define NEEDLE_PLAN_J_MAX_DFLT 2467.105263

#endif /* NEEDLE_LIMITS_OVERRIDE_H */
